# Generated by Django 5.2.4 on 2026-04-06 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nombre del lugar')),
                ('description', models.TextField(verbose_name='¿Por qué es genial este lugar?')),
                ('location', models.CharField(help_text='Ej: Cabo de Gata, Almería o una dirección específica', max_length=255, verbose_name='Ubicación')),
                ('image', models.ImageField(upload_to='destinations/', verbose_name='Foto del lugar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
