# Generated by Django 5.2.4 on 2026-04-06 20:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destination_image_destinationimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='¿Por qué es genial este lugar?'),
        ),
    ]
