# Generated by Django 5.2.4 on 2025-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='berths',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazas para dormir'),
        ),
        migrations.AddField(
            model_name='listing',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('DIESEL', 'Diésel'), ('GASOLINE', 'Gasolina'), ('ELECTRIC', 'Eléctrico'), ('HYBRID', 'Híbrido'), ('LPG', 'GLP'), ('OTHER', 'Otro')], max_length=10, null=True, verbose_name='Combustible'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_air_conditioning',
            field=models.BooleanField(default=False, verbose_name='Aire acondicionado'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_bathroom',
            field=models.BooleanField(default=False, verbose_name='Baño con WC'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_heating',
            field=models.BooleanField(default=False, verbose_name='Calefacción'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_kitchen',
            field=models.BooleanField(default=False, verbose_name='Cocina'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_shower',
            field=models.BooleanField(default=False, verbose_name='Ducha'),
        ),
        migrations.AddField(
            model_name='listing',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Longitud (m)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometraje (km)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='pets_allowed',
            field=models.BooleanField(default=False, verbose_name='Admite mascotas'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazas para viajar'),
        ),
        migrations.AddField(
            model_name='listing',
            name='transmission',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automática')], max_length=10, null=True, verbose_name='Transmisión'),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Peso (MMA en kg)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fabricación'),
        ),
    ]
