# Generated by Django 5.2.4 on 2026-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_berths_listing_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CARAVANA', 'Caravana'), ('AUTOCARAVANA', 'Autocaravana'), ('CAMPER', 'Camper'), ('ACCESORIO', 'Accesorio')], default='CARAVANA', max_length=20, verbose_name='Categoría'),
        ),
    ]
