# Generated by Django 5.2.4 on 2026-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_solar_panels',
            field=models.BooleanField(default=False, verbose_name='Placas solares'),
        ),
    ]
