# Generated by Django 5.2.4 on 2026-04-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_type',
            field=models.CharField(choices=[('PRIVATE', 'Particular'), ('PROFESSIONAL', 'Profesional')], default='PRIVATE', max_length=15, verbose_name='Tipo de vendedor'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('CARAVANA', 'Caravana'), ('AUTOCARAVANA', 'Autocaravana'), ('CAMPER', 'Camper')], default='CARAVANA', max_length=20, verbose_name='Categoría'),
        ),
    ]
