# Generated by Django 5.2.4 on 2026-04-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_seller_type_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('SALE', 'Venta')], default='SALE', max_length=10, verbose_name='Tipo de anuncio'),
        ),
    ]
