# Generated by Django 5.2.4 on 2026-04-16 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_listing_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_listings', to=settings.AUTH_USER_MODEL, verbose_name='Me gusta'),
        ),
    ]
