# Generated by Django 5.1.3 on 2026-09-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="submission_token",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
