# Generated by Django 5.2.4 on 2025-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=10, verbose_name='Estado'),
        ),
    ]
