# Generated by Django 5.2.4 on 2026-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descripción para buscadores (Google). Máx 160 caracteres.', max_length=160, verbose_name='Meta descripción'),
        ),
    ]
