# Generated by Django 5.2.4 on 2026-04-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_meta_description'),
        ('blog', '0006_post_meta_description'),
    ]

    operations = [
    ]
