# Generated by Django 5.2.4 on 2026-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_merge_20260428_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen externa'),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='Imagen'),
        ),
    ]
