# Generated by Django 5.2.4 on 2026-04-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postimage_image_url_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado')], default='PUBLISHED', max_length=10, verbose_name='Estado'),
        ),
    ]
