from django.db import migrations
from urllib.parse import quote_plus

TAG = "caravaning0a-21"
AUTHOR_USERNAME = "miguel"

POSTS = [
    {"slug":"mejores-accesorios-para-viajar-en-camper-en-verano","title":"15 accesorios para viajar en camper en verano que realmente merecen la pena","meta":"Los 15 accesorios más útiles para viajar en camper en verano: sombra, ventilación, cocina, energía, organización y comodidad.","cover":"https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1600&q=85","intro":"El verano es una de las mejores épocas para viajar en camper, pero también pone a prueba el vehículo: calor, poco espacio, baterías, duchas, cocina y noches con temperaturas altas. Hemos seleccionado accesorios prácticos que pueden mejorar mucho una escapada.","products":[("Ventilador recargable para camper","ventilador recargable camping camper"),("Toldo o parasol para camping","toldo parasol camping camper"),("Silla plegable de camping","silla plegable camping ligera"),("Mesa plegable de camping","mesa plegable camping aluminio"),("Ducha portátil","ducha portatil camping bateria"),("Nevera portátil","nevera portatil camping 12v"),("Power bank de 20.000 mAh","power bank 20000mah camping"),("Lámpara LED recargable","lampara LED camping recargable"),("Mosquitera para camping","mosquitera camping camper"),("Organizador para camper","organizador camper autocaravana"),("Botellas térmicas","botella termica acero camping"),("Tendedero portátil","tendedero portatil camping"),("Cocina de camping compacta","cocina camping portatil"),("Linterna frontal","linterna frontal recargable camping"),("Alfombra exterior para camping","alfombra exterior camping camper")]},
    {"slug":"mejor-kit-cocina-camper-accesorios","title":"El kit de cocina camper perfecto: 15 accesorios que ocupan poco y solucionan mucho","meta":"Prepara una cocina camper práctica con estos 15 accesorios: menaje, almacenamiento, café, limpieza y organización.","cover":"https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1600&q=85","intro":"Una buena cocina camper no necesita veinte armarios. Necesita accesorios que aprovechen el espacio, sean fáciles de limpiar y puedan guardarse rápidamente.","products":[("Set de menaje compacto","set menaje camping cocina completo"),("Sartén plegable o compacta","sarten camping plegable"),("Cazo de camping","cazo camping acero inoxidable"),("Tabla de cortar plegable","tabla cortar plegable camping"),("Cuchillos de cocina compactos","set cuchillos cocina camping"),("Escurridor plegable","escurridor plegable camping"),("Recipientes herméticos","recipientes hermeticos cocina camping"),("Organizador de cocina","organizador cocina camper"),("Cafetera italiana","cafetera italiana camping"),("Hervidor compacto","hervidor electrico compacto camping"),("Encendedor largo de cocina","encendedor cocina largo"),("Paños de microfibra","paños microfibra cocina pack"),("Cubos de basura compactos","papelera cocina compacta camping"),("Estropajo y dispensador","dispensador jabon fregadero cocina"),("Bolsas reutilizables","bolsas silicona reutilizables cocina")]},
    {"slug":"energia-solar-camper-accesorios-imprescindibles","title":"Energía para una camper: 12 accesorios para tener electricidad cuando estás fuera de camping","meta":"Guía de accesorios para mejorar la autonomía eléctrica de una camper: placas solares, baterías, cargadores, inversores y monitorización.","cover":"https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1600&q=85","intro":"Cuando pasas varios días fuera de un camping, la energía se convierte en una cuestión clave. Algunos accesorios sencillos pueden ayudarte a aprovechar mejor la batería y reducir la dependencia de enchufes.","products":[("Panel solar portátil","panel solar portatil camping 100w"),("Cargador solar USB","cargador solar USB camping"),("Power station portátil","estacion energia portatil camping"),("Cargador USB-C PD","cargador USB C PD coche camper"),("Medidor de consumo eléctrico","medidor consumo bateria 12v"),("Inversor 12V a 230V","inversor 12v 230v camper"),("Alargador eléctrico de camping","alargador electrico camping carrete"),("Regleta compacta","regleta compacta USB C"),("Batería externa de alta capacidad","power bank alta capacidad camping"),("Linterna recargable USB","linterna recargable USB camping"),("Luz LED con sensor","luz LED sensor movimiento camper"),("Cables USB-C resistentes","cables USB C resistentes pack")]},
    {"slug":"dormir-fresco-camper-verano","title":"Cómo dormir fresco en una camper en verano: 12 accesorios que sí ayudan","meta":"Descubre cómo dormir mejor en una camper durante las noches calurosas con ventilación, mosquiteras, textiles y accesorios prácticos.","cover":"https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=85","intro":"Dormir en una camper en una noche de verano puede ser maravilloso o una batalla contra el calor. Hay pequeños cambios que mejoran mucho la ventilación y el confort sin hacer una gran instalación.","products":[("Ventilador recargable silencioso","ventilador silencioso recargable camping"),("Mosquitera magnética","mosquitera magnetica puerta camping"),("Cortinas térmicas","cortinas termicas camper autocaravana"),("Sábana de algodón ligera","sabanas algodon verano camper"),("Almohada de viaje transpirable","almohada transpirable camping"),("Colchoncillo refrigerante","esterilla refrigerante verano"),("Termómetro digital interior","termometro digital interior camping"),("Luz de lectura USB","luz lectura USB cama camping"),("Power bank","power bank 20000mah camping"),("Mini ventilador de pinza","mini ventilador pinza recargable"),("Parasol térmico","parasol termico autocaravana camper"),("Toalla de microfibra","toalla microfibra grande camping")]},
    {"slug":"seguridad-camper-accesorios-imprescindibles","title":"Seguridad en camper y autocaravana: 15 accesorios económicos que merece la pena llevar","meta":"15 accesorios de seguridad para camper y autocaravana: detectores, iluminación, herramientas, señalización y emergencia.","cover":"https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=85","intro":"La seguridad no tiene por qué significar llenar la camper de dispositivos. Hay accesorios económicos que ayudan a prevenir problemas, detectar incidencias y estar mejor preparado ante una avería o emergencia.","products":[("Detector de monóxido de carbono","detector monoxido carbono camping"),("Detector de humo","detector humo camper autocaravana"),("Extintor compacto homologado","extintor compacto coche autocaravana"),("Linterna potente","linterna potente recargable camping"),("Luz de emergencia V16","luz emergencia V16 homologada DGT"),("Kit de primeros auxilios","botiquin primeros auxilios camping"),("Kit de herramientas","kit herramientas coche camping"),("Manómetro digital","manometro digital neumaticos coche"),("Compresor portátil 12V","compresor portatil 12v coche"),("Cables de arranque","cables arranque coche largos"),("Candado de seguridad","candado seguridad camping autocaravana"),("Cámara de vigilancia portátil","camara vigilancia portatil wifi"),("Silbato de emergencia","silbato emergencia supervivencia"),("Chaleco reflectante","chaleco reflectante homologado coche"),("Manta térmica de emergencia","manta termica emergencia camping")]},
]

def amazon_url(query):
    return f"https://www.amazon.es/s?k={quote_plus(query)}&tag={TAG}"

def build_content(data):
    body = [f'<img src="{data["cover"]}" alt="{data["title"]}" style="width:100%;height:auto;aspect-ratio:16/9;object-fit:cover;border-radius:18px;margin-bottom:24px;">',f'<p>{data["intro"]}</p>','<div style="margin:24px 0;padding:18px;border-radius:14px;background:#f5f5f5;"><strong>🛒 Consulta los accesorios seleccionados en Amazon.</strong> El precio y la disponibilidad pueden cambiar, así que comprueba siempre la ficha antes de comprar.</div>']
    for i,(name,query) in enumerate(data["products"],1):
        url=amazon_url(query)
        body.append(f'<h2>{i}. {name}</h2>')
        body.append(f'<p><strong>Por qué interesa para una camper:</strong> es un accesorio pensado para resolver una necesidad concreta durante el viaje. Antes de comprar, revisa medidas, compatibilidad, autonomía y opiniones recientes.</p>')
        body.append(f'<p><a href="{url}" target="_blank" rel="nofollow sponsored noopener" style="display:inline-block;padding:12px 18px;border-radius:10px;background:#ff9900;color:#111;text-decoration:none;font-weight:700;">🛒 Ver {name} en Amazon</a></p>')
    body.extend(['<h2>Qué comprar primero</h2>','<p>No necesitas comprarlo todo. Empieza por los accesorios que solucionan un problema que ya hayas tenido en tus viajes. Si viajas mucho, prioriza seguridad, energía y organización; después añade comodidad.</p>','<h2>Consejo antes de comprar</h2>','<p>Compara medidas, consumo eléctrico, autonomía, materiales y opiniones. En accesorios para vehículos y camping, la compatibilidad importa más que comprar simplemente lo más barato.</p>','<div style="margin:28px 0;padding:16px;border:1px solid #ddd;border-radius:12px;"><strong>Nota de afiliación:</strong> Algunos enlaces de este artículo son enlaces de afiliado. Si realizas una compra después de acceder a ellos, Caravaning Project puede recibir una comisión sin coste adicional para ti. Los precios y la disponibilidad pueden cambiar.</div>'])
    return ''.join(body)

def create_posts(apps,schema_editor):
    Post=apps.get_model("blog","Post")
    User=apps.get_model("auth","User")
    author=User.objects.filter(username=AUTHOR_USERNAME).first() or User.objects.filter(is_superuser=True).first()
    if not author:return
    for data in POSTS:
        post,created=Post.objects.get_or_create(slug=data["slug"],defaults={"author":author,"title":data["title"],"content":build_content(data),"meta_description":data["meta"],"status":"PUBLISHED"})
        if not created:
            post.author=author;post.title=data["title"];post.content=build_content(data);post.meta_description=data["meta"];post.status="PUBLISHED";post.save()

def remove_posts(apps,schema_editor):
    Post=apps.get_model("blog","Post")
    Post.objects.filter(slug__in=[p["slug"] for p in POSTS]).delete()

class Migration(migrations.Migration):
    dependencies=[("blog","0019_mejorar_imagenes_accesorios")]
    operations=[migrations.RunPython(create_posts,remove_posts)]
