# Generated by Django 5.1.3 on 2026-09-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0092_imagenes_generadas_alquiler_camper_sevilla"),
        ("shop", "0009_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="shop_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="blog_posts",
                to="shop.product",
                verbose_name="Productos relacionados",
            ),
        ),
    ]
