# Generated by Django 5.2.4 on 2026-04-02 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de tienda',
                'verbose_name_plural': 'Categorías de tienda',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='shop_products/', verbose_name='Imagen')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio aproximado (€)')),
                ('affiliate_url', models.URLField(max_length=1000, verbose_name='Enlace de afiliado')),
                ('button_text', models.CharField(default='Ver oferta en Amazon', max_length=50, verbose_name='Texto del botón')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
