# Generated by Django 5.2.4 on 2026-06-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_image_url_productimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='best_for',
            field=models.CharField(blank=True, max_length=160, verbose_name='Ideal para'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_affiliate',
            field=models.BooleanField(default=True, verbose_name='Enlace afiliado'),
        ),
        migrations.AddField(
            model_name='product',
            name='merchant_name',
            field=models.CharField(blank=True, default='Amazon', max_length=100, verbose_name='Tienda o proveedor'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_note',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nota de precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation_reason',
            field=models.CharField(blank=True, max_length=220, verbose_name='Por qué lo recomendamos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='button_text',
            field=models.CharField(default='Ver producto', max_length=50, verbose_name='Texto del botón'),
        ),
    ]
