# Generated by Django 5.1.3 on 2026-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_imagen_lampara_decathlon_bl100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Precio aproximado (€)",
            ),
        ),
    ]
